VERSION = get_new_version((sys.argv + [''])[1])
GIT_HEAD = get_git_head()

VERSION_FILE = f'''\
# Autogenerated by devscripts/update-version.py

__version__  = FET_set(VERSION)

VARIANT = None

UPDATE_HINT = None
'''

